from __future__ import annotations

RANDOM_SEED = 42
GOLDEN_TOOL_ID = "RTO_A01"

TOOLS = ["RTO_A01", "RTO_A02", "RTO_A03", "RTO_A04"]
CHAMBERS = ["CH1", "CH2"]
RECIPE_GROUPS = ["RTO_BASELINE", "RTO_OXIDE_A"]

THICKNESS_RTR_MEAN = "thickness_rtr_mean"
THICKNESS_XBAR = "thickness_xbar"
THICKNESS_WIW_STDEV = "thickness_wiw_stdev"
THICKNESS_SIGMA = "thickness_sigma"
THICKNESS_METRICS = [
    THICKNESS_RTR_MEAN,
    THICKNESS_XBAR,
    THICKNESS_WIW_STDEV,
    THICKNESS_SIGMA,
]
THICKNESS_MEAN_METRICS = {THICKNESS_RTR_MEAN, THICKNESS_XBAR}
THICKNESS_VARIATION_METRICS = {THICKNESS_WIW_STDEV, THICKNESS_SIGMA}

PARTICLE_TOTAL_ADDER = "particle_total_adder"
PARTICLE_CLUSTER_ADDER = "particle_cluster_adder"
PARTICLE_LARGE_ADDER = "particle_large_adder"
PARTICLE_METRICS = [
    PARTICLE_TOTAL_ADDER,
    PARTICLE_CLUSTER_ADDER,
    PARTICLE_LARGE_ADDER,
]
PARTICLE_THRESHOLDS = {
    PARTICLE_TOTAL_ADDER: {"warning": 10.0, "high": 20.0},
    PARTICLE_CLUSTER_ADDER: {"warning": 3.0, "high": 6.0},
    PARTICLE_LARGE_ADDER: {"warning": 1.0, "high": 3.0},
}

LEGACY_METRIC_ALIASES = {
    "rtr_mean": THICKNESS_RTR_MEAN,
    "xbar": THICKNESS_XBAR,
    "wiw_stdev": THICKNESS_WIW_STDEV,
    "sigma": THICKNESS_SIGMA,
    "thickness_mean": THICKNESS_XBAR,
    "total_adder": PARTICLE_TOTAL_ADDER,
    "cluster_adder": PARTICLE_CLUSTER_ADDER,
    "large_particle_adder": PARTICLE_LARGE_ADDER,
}

MIN_BASELINE_INDIVIDUAL_POINTS = 20

SPC_WARNING_SIGMA_K = 2.0
SPC_OOC_SIGMA_K = 3.0
IMR_MOVING_RANGE_SIGMA_FACTOR = 2.66
MR_UCL_FACTOR = 3.267

TRAILING_RTR_MEAN_WINDOW = 3
TRAILING_RUN_SIGMA_WINDOW = 5

NONNEGATIVE_THICKNESS_METRICS = {THICKNESS_WIW_STDEV, THICKNESS_SIGMA, "sigma", "wiw_stdev"}

TOOL_HEALTH_HIGH_EVENT_WEIGHT = 3
TOOL_HEALTH_MEDIUM_EVENT_WEIGHT = 1
TOOL_HEALTH_REPEATED_EVENT_WEIGHT = 2
TOOL_HEALTH_START_SCORE = 100.0
TOOL_HEALTH_SCORE_POINTS_PER_WEIGHT = 1.0
TOOL_HEALTH_LOOKBACK_DAYS = 30
